---
# title: "Eurostat Cheat‑Sheet"
date: "`r Sys.Date()`"
header-includes:
  \usepackage{pdflscape,multicol,blindtext}
  \usepackage{xcolor}
output:
  pdf_document
geometry: margin = 0.1in
---

<!-- 
  \usepackage[poster]{tcolorbox}
  \usepackage{minted2}
  \tcbuselibrary{minted}
  \definecolor{babyblue}{rgb}{0.54, 0.81, 0.94}
  \newtcolorbox{coloredcols}{
    colback=white,
    colframe=babyblue
  }
  \newtcolorbox{coloredcols}{
  colback=white,
  colframe=babyblue,
  rounded corners,
  arc=1pt,
  boxrule=0pt,
  left=0pt,
  right=0pt,
  top=2pt,
  bottom=2pt,
  before skip=1pt,
  after skip=1pt,
} -->

```{=latex}
\thispagestyle{empty}
\begin{landscape}
\begin{multicols}{2}
```
<!-- \begin{coloredcols} -->
<!-- \begin{multicols}{3} -->

# The *eurostat* package
## R tools to access open data from Eurostat database

## Search and download

Data in the Eurostat database is stored in tables.
Each table has an identifier, a short table_code, and 
a description (e.g. tsdtr420 - People killed in road accidents).
Key eurostat functions allow to find the table_code, 
download the eurostat table and polish labels in the table.

### Get the Eurostat Table of Content

The **get_eurostat_toc(lang="en")** function downloads 
the table of contents (TOC) of eurostat datasets.

```
library("eurostat")
toc <- get_eurostat_toc(
  lang="en" 
)
toc
##   title       code  type  last.update.of.data last.table.structure… data.start
## 1 Database b… data  fold… " "                 " "                    " "       
## 2 General an… gene… fold… " "                 " "                    " "       
## 3 European a… euro… fold… " "                 " "                    " "       
```

### Get all datasets in a folder

<!-- TODO this because it does not work the download w/o specifying the number of datasets... -->
With the code entry from the previous function, 
you can loop over all files in a Eurostat database folder, download the
data and assign the datasets to an environment via **get_eurostat_folder(code, env = .EurostatEnv)**.


### Find the table code

The **search_eurostat(pattern, ...)** function scans the directory 
of Eurostat tables and returns codes and descriptions of 
tables that match pattern.

```
query <- search_eurostat(
  pattern="road", 
  type="table", 
)
query[1:3, 1:2]
##   title                       code 
## 1 Goods transport by road     ttr0…
## 2 Final energy consumption... ten0…
## 3 Direct investment abroad... tips…
```

### Download the table

The **get_eurostat(id, time_format="date", filters=NULL, type="code", cache=TRUE, ...)** 
function downloads the requested table from the *Eurostat bulk download facility* or
from *The Eurostat Web Services JSON API* (if **filters** are defined). 
Downloaded data is cached (**if cache=TRUE**). 
Additional arguments define how to read the time column
(**time_format**) and if table dimensions shall be kept as 
codes or converted to labels (**type**).

```
dat <- get_eurostat(
  id="tps00199", 
  time_format="num"
)
dat[1:2,]
##   freq  indic_de geo   TIME_PERIOD values
## 1 A     TOTFERRT AL           2013   1.73
## 2 A     TOTFERRT AL           2014   1.73
```

#### In JSON format

The **get_eurostat_json(id, filters=NULL, type="code", lang="en", ...)** 
function downloads the requested table in JSON format.

#### In Interactive mode

The **get_eurostat_interactive(code = NULL)** function can be used with 
**code** from **search_eurostat()**. It is a simple interactive helper function 
to go through the steps of downloading and/or finding suitable eurostat datasets.



### Add labels

The **label_eurostat(x, lang="en", ...)** gets definitions for Eurostat
codes and replace them with labels in given language ("en", "fr" or "de")

```
dat <- label_eurostat(dat)
dat[1:3,2:5]
##   indic_de     geo     TIME_PERIOD values
## 1 Total fer... Albania        2013   1.73
## 2 Total fer... Albania        2014   1.73
## 3 Total fer... Albania        2015   1.59
```

Similary, for tables you can use **label_eurostat_tables(x, lang="en")**.

## Validate geo codes

You can validate your geo codes, pair them with the appropriate standard
typology, look up potential causes of invalidity in the EU
correspondence tables, and look up the appropriate geographical
codes in the other (target) typology. 
For instance, **recode_nuts(dat, geo_var = "geo", nuts_year = 2016)**.

You can then validate that 'geo' is conforming with the 'NUTS1', 'NUTS2', or
'NUTS3' typologies. While country codes are technically not part
of the NUTS typologies, Eurostat de facto uses a 'NUTS0' typology
to identify countries.
**validate_geo_code(geo, nuts_year = 2016)**
You can also validate that 'geo_var' is conforming with the 'NUTS1', 'NUTS2',
or 'NUTS3' typologies, with **validate_nuts_regions(dat, geo_var = "geo", nuts_year = 2016)**.


## The eurostat cache

### List the items in the cache

You can list all the items in the cache via **list_eurostat_cache_items(cache_dir = NULL)**. 
It returns a data.frame.

### Clean the cache

You can clean the eurostat cache directory, deleting all the .rds files, 
with **clean_eurostat_cache(cache_dir = NULL, config = FALSE)**. 
You can change the **config** parameter to decide whether to delete the cached path.
You can find more about the cache with **get_eurostat()**


```{=latex}
\end{multicols}
\end{landscape}
```

<!-- ## eurostat and plots

The get_eurostat() function returns tibbles in the long format. Packages
dplyr and tidyr are well suited to transform these objects. The ggplot2
package is well suited to plot these objects. 

```
dat <- get_eurostat(id="tps00199", filters = list(geo = ct))
library(ggplot2)
library(dplyr)
ggplot(dat, 
       aes(x = time, y = values, color = geo, label = geo)) +
  geom_line(alpha = .5) +
  geom_text(data = dat %>% group_by(geo) %>% 
              filter(time == max(time)), 
            size = 2.6) + 
  theme(legend.position = "none") +
  labs(title = "Total fertility rate, 2006-2017", 
       x = "Year", y = "%") -> p
``` -->
