library(knitr)
library(rmarkdown)
render("vignette.Rmd", output_format = "md_document")
# render("vignette.Rmd", output_format = "pdf_document")
render("vignette.Rmd", output_format = "html_document")

#knit("vignette.Rmd")
#knit("manuscript.Rmd")
#render("manuscript.Rmd", output_format = "html_document")
#render("manuscript.Rmd", output_format = "pdf_document")
#knit2pdf("eurostat.Rnw")
#library(rmarkdown)
#render("vignette.Rmd", output_format = "pdf_document")
