#' @import methods
#' @importFrom broom tidy
#' @importFrom classInt classIntervals
#' @importFrom dplyr %>%
#' @importFrom dplyr filter
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr filter
#' @importFrom dplyr left_join
#' @importFrom httr build_url
#' @importFrom httr content
#' @importFrom httr GET
#' @importFrom httr status_code
#' @importFrom jsonlite fromJSON
#' @importFrom RColorBrewer brewer.pal
#' @importFrom readr read_tsv
#' @importFrom readr col_character
#' @importFrom sf st_read
#' @importFrom sp merge
#' @importFrom sp spplot
#' @importFrom stringi stri_match_first_regex
#' @importFrom stringr str_replace_all
#' @importFrom stats lag
#' @importFrom tibble data_frame
#' @importFrom tibble is_tibble
#' @importFrom tibble as_data_frame
#' @importFrom tidyr separate
#' @importFrom tidyr gather_
#' @importFrom utils download.file
#' @importFrom methods as
#' @importFrom utils data
.EurostatEnv <- new.env()
