# Workflow derived from https://github.com/r-lib/actions/blob/master/.github/workflows/render-readme.yaml
# and https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/
# Workflow triggering derived from: https://stevenmortimer.com/running-github-actions-sequentially/
on:
  workflow_dispatch:

# This is triggered manually

    
name: Tidy code

jobs:
  tidy:
    name: Tidy code
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r@master
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@master
        with:
          extra-packages: |
            usethis
            styler
            urlchecker
            devtools
            roxygen2
            
          needs: website
      - name: Tidy code
        run: |
          usethis::use_tidy_description()
          tools::resaveRdaFiles("data")
          tools::resaveRdaFiles("R")
          styler::style_pkg(filetype = c("R", "Rmd"))
          urlchecker::url_update()
          devtools::build_readme()
          roxygen2::roxygenise()
        shell: Rscript {0}
        
      
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m 'Tidy code' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
      - name: Trigger pkgdown workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-pkgdown-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'